version: "3.7"

services:
  frontend:
    image: node:14-alpine
    command: sh -c "cd frontend && yarn build && yarn start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
  api-server:
    image: node:14-alpine
    command: sh -c "cd backend && yarn install && yarn api-server"
    ports:
      - 4000:4000
    working_dir: /api-server
    volumes:
      - ./:/api-server
  socket-server:
    image: node:14-alpine
    command: sh -c "cd backend && yarn install && yarn socket-server"
    ports:
      - 5000:5000
    working_dir: /socket-server
    volumes:
      - ./:/socket-server
  redis:
    image: redis
    ports:
      - "6379:6379"
